return function()
    local Communicator = require(script.Parent.Communicator)
    require(game.ReplicatedStorage.WorldConfig).Init()
    local BehaviorHandler = require(game.ReplicatedStorage.BehaviorHandler)
    BehaviorHandler.loadComponet("Biomes")
    BehaviorHandler.loadComponet("Structures")
    BehaviorHandler.loadComponet("Ores")
    BehaviorHandler.loadComponet("Foilage")
    --BehaviorHandler.loadComponet("Blocks")
    local Blocks = require(game.ReplicatedStorage.Block).Init()
    local biomes = require(game.ReplicatedStorage.Biomes)
    local Registry = require(script.Parent.Registry)
    biomes.init()
    Communicator.runParallel(function()
        Registry.init()
    end)
end
