local BehaviorHandler = require(game.ReplicatedStorage.BehaviorHandlerV2)
BehaviorHandler.Init()
local RunService = game:GetService("RunService")
local resource =require(game.ReplicatedStorage.ResourceHandler)
local ServerReplicator = require(game.ReplicatedStorage.EntityHandlerV2.EntityReplicator.Server)
local Utils = require(game.ReplicatedStorage.EntityHandlerV2.Utils)
ServerReplicator.Init()
local hold = require(game.ReplicatedStorage.EntityHandlerV2.EntityHolder)
local Handler = require(game.ReplicatedStorage.EntityHandlerV2)
local EntityBehavior = require(game.ServerStorage.ServerEntity.EntityBehaviorHandler)
EntityBehavior.Init()
local EntityUpdater = require(game.ReplicatedStorage.EntityHandlerV2.Updater)
EntityUpdater.Init()
local NPC = Handler.new("Npc")
NPC.Position = Vector3.new(342, 63.5, -77)
hold.addEntity(NPC)
game.Players.PlayerAdded:Connect(function(player: Player)  
    local entity = Handler.new("Player",player.UserId)
    entity.Position = Vector3.new(342, 63.4, -77)
    Handler.setOwner(entity,player)
    hold.addEntity(entity)
end)