local BehaviorHandler = require(game.ReplicatedStorage.BehaviorHandler)
BehaviorHandler.Init()
local RunService = game:GetService("RunService")
local resource =require(game.ReplicatedStorage.ResourceHandler)
local ServerReplicator = require(game.ServerStorage.core.Entity.EntityReplicatorServer)
local Utils = require(game.ReplicatedStorage.EntityHandler.Utils)
ServerReplicator.Init()
local hold = require(game.ReplicatedStorage.EntityHandler.EntityHolder)
local Handler = require(game.ReplicatedStorage.EntityHandler)
local EntityBehavior = require(game.ServerStorage.core.Entity.EntityBehaviorHandler)
EntityBehavior.Init()
local EntityUpdater = require(game.ReplicatedStorage.EntityHandler.Updater)
EntityUpdater.Init()
local IndexUtils = require(game.ReplicatedStorage.Utils.IndexUtils)
IndexUtils.preComputeAll()

require(game.ServerStorage.core.Chunk)
local NPC = Handler.new("Npc")
NPC.Position = Vector3.new(0, 257.395999908447266, 0)
hold.addEntity(NPC)
game.Players.PlayerAdded:Connect(function(player: Player)  
    local entity = Handler.new("Player",player.UserId)
    entity.Position = Vector3.new(522//3, 257.395999908447266, -671.44//3)
    Handler.setOwner(entity,player)
    hold.addEntity(entity)
end)